### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sazonovOleg** [sazonovOleg/TSReactDashboard#7]
- [x] Сделать всю область карточки кликабельной для открытия задачи и ховер эффект
- [x] бордер радиус у карточки скруглить и проверить остальные
- [x] доделать editable form для тантал и дескрипшена и чтобы сохранение работало по  нажатию  на Энтер
- [x] убрать белое поле после комментариев
- [x] убрать большой белый отступ у списка задач
- [ ]
